name: Build

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Build
        run: |
          yarn add prettier
          yarn run lint
          yarn run build
